function(cc_test)
  set(options "")
  set(oneValueArgs NAME STANDARD)
  set(multiValueArgs SRCS)
  cmake_parse_arguments(TEST "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if (NOT DEFINED TEST_STANDARD)
    set(TEST_STANDARD 20)
  endif()
#  message("${TEST_NAME}, ${TEST_SRCS}, ${TEST_STANDARD}")
  set(EXEC "${TEST_NAME}")
  add_executable(${EXEC} ${TEST_SRCS})
  set_target_properties(${EXEC} PROPERTIES CXX_STANDARD ${TEST_STANDARD})
  target_link_libraries(${EXEC} PRIVATE ${GTEST_LIBRARIES} GTest::gtest_main Threads::Threads)

#  message("${TEST_NAME}, ${EXEC}")
  add_test(NAME ${TEST_NAME} COMMAND ${EXEC})
endfunction()
